sudo: false

language: python

python:
  - '3.6.5'
  - pypy3

before_install:
  - pip install hacking
  - flake8 .

install:
  - python setup.py install

script:
  # other than google drive
  - output=/tmp/gdown_r
  - gdown 'https://raw.githubusercontent.com/wkentaro/gdown/3.1.0/gdown/__init__.py' -O $output --quiet
  - test $(md5sum $output | awk '{print $1}') = 2a51927dde6b146ce56b4d89ebbb5268
  # small file
  - output=/tmp/spam.txt
  - gdown 'https://drive.google.com/uc?id=0B9P1L--7Wd2vU3VUVlFnbTgtS2c' -O $output --quiet
  - test $(cat $output) = spam
  # large file
  - output=/tmp/apc2015_object_images.tgz
  - gdown 'https://drive.google.com/uc?id=0B9P1L--7Wd2vNm9zMTJWOGxobkU' -O $output --quiet
  - test $(md5sum $output | awk '{print $1}') = fa837a88f0c40c513d975104edf3da17
  # streaming/piping files
  - output=/tmp/spam.txt
  - gdown 'https://drive.google.com/uc?id=0B9P1L--7Wd2vU3VUVlFnbTgtS2c' -s > spam_pipe.txt
  - md5sum spam_pipe.txt > /tmp/spam_pipe.txt.md5
  - cat $output | md5sum --check /tmp/spam_pipe.txt.md5
